### ISSUE TITLE
Warning in development

### ISSUE THREAD

**Issue by enBonnet** [supabase/supabase-ui-web#19]
# Bug report

## Describe the bug

When we execute the project in development will get some warnings.

## To Reproduce

1. Clone repository
2. `npm install`
3. `npm run dev`
4. See warnings

## Expected behavior

We should not have warnings

## Screenshots

<img width="1278" alt="Captura de Pantalla 2021-07-31 a la(s) 08 40 30" src="https://user-images.githubusercontent.com/13243693/127740474-8c06140f-38c9-4b82-90e1-f3dd057d1b52.png">

## System information

- OS: macOS
- Browser (if applies): n/a
- Version of supabase-js: n/a
- Version of Node.js: v14.17.0

**Comment by Mayank-MP05** [comment]
Hey @enBonnet it seems like a simple react type warning coming from misspelling className instead of class
