### ISSUE TITLE
The Auth demo is sending out magic link emails

### ISSUE THREAD

**Issue by BharatKalluri** [supabase/supabase-ui-web#4]
# Bug report

## Describe the bug

The [auth demo](https://ui.supabase.io/components/auth#getting-started) is actually sending out magic link emails. I'm not sure if that's intentional. If it is, feel free to close this bug report. 😃 

## To Reproduce

- Go to https://ui.supabase.io/components/auth#getting-started
- Click on "Send magic link"
- enter email and submit

## Expected behavior

I think there should be some kind of error instead of actually sending out an email

**Comment by kiwicopple** [comment]
that's a feature not a bug 😅 

thanks @BharatKalluri - fixing now

**Comment by kiwicopple** [comment]
fixed!
