### ISSUE TITLE
List of supabase icons

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase-ui-web#40]
# Feature request

## Is your feature request related to a problem? Please describe.

A list of all of the supabase icons. Also, be able to search for the icon that you are looking for.

**Comment by MildTomato** [comment]
---

Supabase UI is being deprecated.
We are moving the components to the main mono repo at [github.com/supabase/supabase](http://github.com/supabase/supabase).

This website will probably be removed/taken down in preference for a storybook documentation site.

The auth component has been moved to it's own repo and package. [github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the docs for auth ui here.

In regards to icons, we probably want to move to a setup which allows any icon / svg to be used from major icon sets like heroicons

---
