### ISSUE TITLE
chore: Icon docs are missing from official docs

### ISSUE THREAD

**Issue by Ziinc** [supabase/supabase-ui-web#41]
# Chore

## Describe the chore
Official docs are missing Icon components available as well as how to use examples.

**Comment by MildTomato** [comment]
---

Supabase UI is being deprecated.
We are moving the components to the main mono repo at [github.com/supabase/supabase](http://github.com/supabase/supabase).

This website will probably be removed/taken down in preference for a storybook documentation site.

The auth component has been moved to it's own repo and package. [github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the docs for auth ui here.

---
