### ISSUE TITLE
Sidepanel Code Block bugs

### ISSUE THREAD

**Issue by Neesh774** [supabase/supabase-ui-web#46]
# Bug report

## Describe the bug

As I open a sidepanel demo, the code blocks on the page do not dim with the rest of the website, similar to issue supabase/supabase-ui-web#42, except the code blocks do NOT dim at all

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [The sidepanel demonstration page](https://ui.supabase.com/components/sidepanel)
2. Scroll down to any of the side panel demonstrations
3. Press the 'Open sidepanel' button
4. As the sidepanel opens, the code blocks do not dim with the rest of the website

## Expected behavior

Anything on the website behind the sidepanel fades

## Screenshots

![image](https://user-images.githubusercontent.com/51027259/150411760-fe193a8b-d3a9-4f0b-a55e-e93f6d4aabe8.png)

## System information

- OS: Windows 11
- Browser (if applies) Brave

**Comment by Hallidayo** [comment]
Just to add to this I found that some of the side panel examples do not open on the page. I've taken a video showing what happens:

https://user-images.githubusercontent.com/22655069/156070629-7aba5ae3-3eb4-4b39-a1a9-31c742d16c0d.mov

The basic example seems to open all the time but the others do not.

### System information

- OS: macOS Monterey - version: 12.2.1
- Browser: Google Chrome - version: 98.0.4758.109

**Comment by MildTomato** [comment]
---

Supabase UI is being deprecated.
We are moving the components to the main mono repo at [github.com/supabase/supabase](http://github.com/supabase/supabase).

This website will probably be removed/taken down in preference for a storybook documentation site.

The auth component has been moved to it's own repo and package. [github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the docs for auth ui here.

---
