### ISSUE TITLE
Mobile navigation 

### ISSUE THREAD

**Issue by mzaien** [supabase/supabase-ui-web#5]
# Bug report

## Describe the bug

It is not a bug but a miss behavior, the page does not go to the top when i change route as you can 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to any component page from mobile 
2. Click on drawer 
3. Scroll down to any other component 

## Expected behavior

The drawer should move from the page and we should see the page from the beginning 

## Screenshots
![CleanShot 2021-04-01 at 18 25 20](https://user-images.githubusercontent.com/43112535/113317632-39041880-9318-11eb-9197-e6f8e70a3b48.gif)

## System information

- OS: ios
- Browser: safari
- Version of supabase-js: supabase/ui v1.0
- Version of Node.js: not applicable

**Comment by MildTomato** [comment]
---

Supabase UI is being deprecated.
We are moving the components to the main mono repo at github.com/supabase/supabase.

This website will probably be removed/taken down in preference for a storybook documentation site.

The auth component has been moved to it's own repo and package. github.com/supabase-community/auth-ui. You can also read the docs for auth ui here.

---
