### ISSUE TITLE
SidePanel examples don't work right

### ISSUE THREAD

**Issue by rodbs** [supabase/supabase-ui-web#52]
# Improve documentation

## Link 
https://ui.supabase.com/components/sidepanel
 
## Describe the problem
When you click on the Modal examples I think they take as a reference the top of the page, and as you scroll down you can see the modals

## Describe the improvement

Fix the code

**Comment by MildTomato** [comment]
thanks @rodbs 

the whole website is out of date. All of the examples need updating to use the alpha pre release version.

**Comment by MildTomato** [comment]
---

Supabase UI is being deprecated.
We are moving the components to the main mono repo at [github.com/supabase/supabase](http://github.com/supabase/supabase).

This website will probably be removed/taken down in preference for a storybook documentation site.

The auth component has been moved to it's own repo and package. [github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the docs for auth ui here.

---
