### ISSUE TITLE
How to change the OAuth2 Scope for discord authentication in Supabase UI

### ISSUE THREAD

**Issue by krishnerkar** [supabase/supabase-ui-web#56]
### Discussed in https://github.com/supabase/supabase/discussions/3547

<div type='discussions-op-text'>

<sup>Originally posted by **Krish-Nerkar** October 15, 2021</sup>
I'm using Supabase UI to authenticate with discord, and i was playing around with the nextjs-auth example, i couldn't figure out how to change the authentication scopes for discord OAuth2

![image](https://user-images.githubusercontent.com/49949733/137478308-d15ba90d-3b9e-4e15-b26f-2610dbae930b.png)
</div>

**Comment by awalias** [comment]
hey @Krish-Nerkar  have you tried the `scopes` parameter here? https://supabase.io/docs/reference/javascript/auth-signin#parameters

**Comment by krishnerkar** [comment]
> hey @Krish-Nerkar have you tried the `scopes` parameter here? https://supabase.io/docs/reference/javascript/auth-signin#parameters

@awalias i have already tried that, looks like supabase UI doesnt support that yet

**Comment by MildTomato** [comment]
---

Supabase UI is being deprecated.
We are moving the components to the main mono repo at [github.com/supabase/supabase](http://github.com/supabase/supabase).

This website will probably be removed/taken down in preference for a storybook documentation site.

The auth component has been moved to it's own repo and package. [github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the docs for auth ui here.

---
