### ISSUE TITLE
Assign Me: Dark Mode Docs / Implementation!

### ISSUE THREAD

**Issue by princefishthrower** [supabase/supabase-ui-web#58]
# Feature request

## Is your feature request related to a problem? Please describe.

I see on the docs that dark mode setup is coming soon - is there an ETA on this? I don't want to overstep anybody.

## Describe the solution you'd like

You can assign me this task and I'll finish it, as long as what remains to be defined is clear!

## Describe alternatives you've considered

Light mode :(

## Additional context

Aforementioned documentation link: https://ui.supabase.com/

**Comment by MildTomato** [comment]
---

Supabase UI is being deprecated.
We are moving the components to the main mono repo at [github.com/supabase/supabase](http://github.com/supabase/supabase).

This website will probably be removed/taken down in preference for a storybook documentation site.

The auth component has been moved to it's own repo and package. [github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the docs for auth ui here.

---
